print((0+2*30)-6//2)
print(0%2+(1-6//6))
print("11" + "11")
print("""Privet, Kak dela?""")
print('6=a')
print("'Little'")
print((12,5 * 2))
print('hello')

print('fwf " wffw " wfwfw ')
print('x="n"*2')
